services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: yangbong-api
    expose:
      - "8000"  # nginx가 내부로 붙음
    environment:
      - UVICORN_WORKERS=2
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health').read()"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks: [appnet]

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: yangbong-web
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE=/api
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on: [api]
    networks: [appnet]

  nginx:
    image: nginx:alpine
    container_name: yangbong-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: [web, api]
    networks: [appnet]

networks:
  appnet: {}

